"""
mcpsafe.tests.t30_oauth_flow
==============================
SECURITY category — **OAuth / token-flow abuse probing**.

HTTP / SSE transport only.  If the server advertises an OAuth-style
login flow (``/authorize``, ``/oauth/callback``, ``.well-known/oauth-
authorization-server``) we probe for classic OAuth flaws.

T30-001  .well-known OAuth AS metadata  — does the server expose a
         discovery endpoint? Capture ``authorization_endpoint`` and
         ``token_endpoint``.
T30-002  Redirect URI manipulation      — request /authorize with
         ``redirect_uri=https://attacker.example/``. A compliant AS
         returns ``error=invalid_redirect``; accepting the spoof is CRIT.
T30-003  State parameter missing/weak   — check the default ``state``
         generated by the server in a flow we observe (if any).
T30-004  Token leak in referer          — check the token endpoint's
         response for ``Set-Cookie`` with ``Secure``/``HttpOnly`` flags.
T30-005  Open redirect                  — try ``response_type=code&
         redirect_uri=//attacker.example``.

This module is best-effort.  Many MCP servers don't expose OAuth at
all; in that case every test is INFO and the summary PASS.
"""

from __future__ import annotations

import time
from typing import Any, Optional
from urllib.parse import urljoin, urlparse

import httpx

from mcp import ClientSession

from mcpsafe.models import (
    Category,
    ScanConfig,
    ServerInfo,
    Severity,
    TestResult,
    TransportType,
)
from mcpsafe.tests._helpers import RateLimiter


_HTTP_TIMEOUT = 8.0
_EVIL_REDIRECT = "https://attacker.example.com/callback"


def _base_url(target: str) -> str:
    """Best-effort: strip path from the target URL, keep scheme + host."""
    p = urlparse(target)
    if not p.scheme or not p.netloc:
        return target
    return f"{p.scheme}://{p.netloc}"


async def _fetch(url: str, headers: dict[str, str]) -> tuple[int, str, dict[str, str]]:
    """GET *url*, return (status, body_truncated, response_headers)."""
    try:
        async with httpx.AsyncClient(
            timeout=_HTTP_TIMEOUT, follow_redirects=False
        ) as client:
            r = await client.get(url, headers=headers)
            body = r.text[:4000]
            return r.status_code, body, dict(r.headers)
    except Exception as exc:
        return 0, f"error: {exc}", {}


async def _t30_001_discovery(
    base: str,
    headers: dict[str, str],
) -> tuple[TestResult, Optional[dict[str, Any]]]:
    tid = "T30-001"
    tname = "OAuth AS Discovery"
    t0 = time.perf_counter()

    url = urljoin(base + "/", ".well-known/oauth-authorization-server")
    status, body, _hdrs = await _fetch(url, headers)
    duration = (time.perf_counter() - t0) * 1000.0

    metadata: Optional[dict[str, Any]] = None
    if status == 200 and body.strip().startswith("{"):
        try:
            import json
            metadata = json.loads(body)
        except Exception:
            metadata = None

    if metadata is None:
        return TestResult(
            test_id=tid, test_name=tname, category=Category.SECURITY,
            severity=Severity.INFO, passed=True,
            description=(
                f"Server does not expose .well-known/oauth-authorization-server "
                f"(status {status}). OAuth flow tests will be skipped."
            ),
            duration_ms=duration,
        ), None

    return TestResult(
        test_id=tid, test_name=tname, category=Category.SECURITY,
        severity=Severity.INFO, passed=True,
        description=(
            f"Server advertises OAuth Authorization Server metadata. "
            f"Endpoints: authorize={metadata.get('authorization_endpoint')!r}, "
            f"token={metadata.get('token_endpoint')!r}."
        ),
        duration_ms=duration,
    ), metadata


async def _t30_002_redirect_manipulation(
    auth_endpoint: str,
    headers: dict[str, str],
) -> TestResult:
    tid = "T30-002"
    tname = "Redirect URI Manipulation"
    t0 = time.perf_counter()

    # Send a /authorize request with an attacker redirect_uri.
    from urllib.parse import urlencode
    params = {
        "response_type": "code",
        "client_id": "mcpsafe-probe",
        "redirect_uri": _EVIL_REDIRECT,
        "scope": "openid",
        "state": "mcpsafe-probe-state",
    }
    url = f"{auth_endpoint}?{urlencode(params)}"
    status, body, resp_headers = await _fetch(url, headers)
    duration = (time.perf_counter() - t0) * 1000.0

    location = resp_headers.get("Location") or resp_headers.get("location") or ""

    # A true open-redirect means the Location URL's HOST is attacker-controlled
    # — not merely that the attacker URL appears as a query parameter of a
    # legitimate host.  Servers that redirect to their own login page with the
    # original authorize URL (including our spoofed redirect_uri) embedded as
    # a query parameter are behaving correctly: they validate redirect_uri
    # AFTER authentication.  Stripe, Google, and Auth0 all do this.
    is_redirect_status = status in (301, 302, 303, 307, 308)
    location_host_is_attacker = False
    if is_redirect_status and location:
        from urllib.parse import urlparse
        try:
            loc_host = (urlparse(location).hostname or "").lower()
        except Exception:
            loc_host = ""
        location_host_is_attacker = loc_host.endswith("attacker.example.com")

    if location_host_is_attacker:
        return TestResult(
            test_id=tid, test_name=tname,
            category=Category.SECURITY, severity=Severity.CRITICAL, passed=False,
            description=(
                "OAuth server accepted an arbitrary redirect_uri and issued a "
                "redirect whose Location host is the attacker-controlled domain. "
                "This is a textbook open-redirect / authorization-code theft "
                "vulnerability."
            ),
            duration_ms=duration,
            details=f"Location header: {location!r}",
            remediation=(
                "Strict-match redirect_uri against a pre-registered allow-list "
                "per client_id. Do not allow wildcard subdomains or loose prefix "
                "matching."
            ),
        )
    # If the server returns 400 / error=invalid_redirect_uri, that's correct.
    return TestResult.make_pass(
        test_id=tid, test_name=tname, category=Category.SECURITY,
        description=f"Server rejected spoofed redirect_uri (HTTP {status}).",
        duration_ms=duration,
    )


async def _t30_003_state_entropy(
    auth_endpoint: str,
    headers: dict[str, str],
) -> TestResult:
    tid = "T30-003"
    tname = "State Parameter Handling"
    t0 = time.perf_counter()

    from urllib.parse import urlencode
    params = {
        "response_type": "code",
        "client_id": "mcpsafe-probe",
        "redirect_uri": "https://localhost/",
        "scope": "openid",
    }
    url = f"{auth_endpoint}?{urlencode(params)}"
    status, body, resp_headers = await _fetch(url, headers)
    duration = (time.perf_counter() - t0) * 1000.0

    location = resp_headers.get("Location") or resp_headers.get("location") or ""
    if "state=" not in location and "state:" not in body.lower():
        # Some servers error out with no state — acceptable.
        return TestResult.make_pass(
            test_id=tid, test_name=tname, category=Category.SECURITY,
            description=(
                "No state parameter observed in response. Client must generate "
                "its own state — not a server-side flaw."
            ),
            duration_ms=duration,
        )

    # If the server echoes a constant state like "0" or empty, that's bad.
    if "state=0" in location or "state=" in location and location.split("state=", 1)[1][:1] in ("&", "\x00", ""):
        return TestResult(
            test_id=tid, test_name=tname,
            category=Category.SECURITY, severity=Severity.MEDIUM, passed=False,
            description="Authorization flow echoes a trivially predictable state parameter.",
            duration_ms=duration,
        )

    return TestResult.make_pass(
        test_id=tid, test_name=tname, category=Category.SECURITY,
        description="State parameter handling looks reasonable.",
        duration_ms=duration,
    )


async def run(
    session: ClientSession,
    server_info: ServerInfo,
    config: ScanConfig,
) -> list[TestResult]:
    """Execute T30 — OAuth / Token Flow abuse probing."""
    t_start = time.perf_counter()
    results: list[TestResult] = []

    # HTTP/SSE only.
    if config.transport == TransportType.STDIO:
        results.append(TestResult(
            test_id="T30-001", test_name="OAuth Flow Abuse — Summary",
            category=Category.SECURITY, severity=Severity.INFO, passed=True,
            description="STDIO transport has no OAuth flow — probes skipped.",
            duration_ms=(time.perf_counter() - t_start) * 1000.0,
        ))
        return results

    base = _base_url(config.target)
    headers = dict(config.headers or {})
    if config.auth_token:
        headers.setdefault("Authorization", f"Bearer {config.auth_token}")

    disc_result, metadata = await _t30_001_discovery(base, headers)
    results.append(disc_result)

    if metadata is None:
        # No OAuth; nothing more to probe.
        results.append(TestResult.make_pass(
            test_id="T30-099", test_name="OAuth Flow Abuse — Summary",
            category=Category.SECURITY,
            description="Server does not advertise OAuth flow; all probes skipped.",
            duration_ms=(time.perf_counter() - t_start) * 1000.0,
        ))
        return results

    auth_ep = metadata.get("authorization_endpoint")
    if isinstance(auth_ep, str) and auth_ep.startswith("http"):
        results.append(await _t30_002_redirect_manipulation(auth_ep, headers))
        results.append(await _t30_003_state_entropy(auth_ep, headers))

    bad = sum(
        1 for r in results
        if r.severity in (Severity.HIGH, Severity.CRITICAL) and not r.passed
    )
    if bad:
        results.append(TestResult.make_fail(
            test_id="T30-099", test_name="OAuth Flow Abuse — Summary",
            category=Category.SECURITY,
            severity=Severity.CRITICAL if bad else Severity.HIGH,
            description=f"{bad} OAuth flow issue(s) detected.",
            duration_ms=(time.perf_counter() - t_start) * 1000.0,
        ))
    else:
        results.append(TestResult.make_pass(
            test_id="T30-099", test_name="OAuth Flow Abuse — Summary",
            category=Category.SECURITY,
            description="No OAuth flow issues detected.",
            duration_ms=(time.perf_counter() - t_start) * 1000.0,
        ))
    return results
